import React, { useState, useEffect } from 'react';
import './AdminCategoryGalleryCrud.css';
import { supabase } from '../../lib/supabase';

const AdminCategoryGalleryCrud = ({ token, onAuthError }) => {
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [editingCategory, setEditingCategory] = useState(null);
  
  const [formData, setFormData] = useState({
    name_ar: '',
    name_fr: '',
    name_en: '',
    slug: '',
    description_ar: '',
    description_fr: '',
    description_en: '',
    is_active: true,
    order: 0
  });
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');

  useEffect(() => {
    loadCategories();
  }, []);

  const loadCategories = async () => {
    try {
      setLoading(true);
      setError('');
      
      const { data, error } = await supabase
        .from('category_gallery')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error loading categories:', error);
        setError('Erreur lors du chargement des catégories: ' + error.message);
        return;
      }

      setCategories(data || []);
    } catch (err) {
      console.error('Exception loading categories:', err);
      setError('Erreur de connexion: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const showNotification = (message, type = 'success') => {
    if (type === 'success') {
      setSuccess(message);
      setError('');
    } else {
      setError(message);
      setSuccess('');
    }
    setTimeout(() => {
      setSuccess('');
      setError('');
    }, 5000);
  };

  // Helper function to generate slug from name
  const generateSlug = (name) => {
    if (!name) return null;
    return name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove accents
      .replace(/[^a-z0-9]+/g, '-') // Replace non-alphanumeric with hyphens
      .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
  };

  // Helper function to check if slug exists
  const checkSlugExists = async (slug, excludeId = null) => {
    if (!slug) return false;
    let query = supabase
      .from('category_gallery')
      .select('id')
      .eq('slug', slug);
    
    if (excludeId) {
      query = query.neq('id', excludeId);
    }
    
    const { data, error } = await query;
    return data && data.length > 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setError('');
      setSuccess('');
      
      // Generate slug if empty
      let slug = formData.slug?.trim() || '';
      if (!slug) {
        // Try to generate from name_fr, then name_en, then name_ar
        const nameToUse = formData.name_fr || formData.name_en || formData.name_ar || '';
        slug = generateSlug(nameToUse);
      }
      
      // Ensure slug is unique
      if (slug) {
        const slugExists = await checkSlugExists(slug, editingCategory?.id);
        if (slugExists) {
          // Append timestamp or number to make it unique
          let uniqueSlug = slug;
          let counter = 1;
          while (await checkSlugExists(uniqueSlug, editingCategory?.id)) {
            uniqueSlug = `${slug}-${counter}`;
            counter++;
          }
          slug = uniqueSlug;
        }
      }
      
      // Prepare category data - explicitly exclude id to avoid primary key conflicts
      const categoryData = {
        name_ar: formData.name_ar?.trim() || null,
        name_fr: formData.name_fr?.trim() || null,
        name_en: formData.name_en?.trim() || null,
        slug: slug || null,
        description_ar: formData.description_ar?.trim() || null,
        description_fr: formData.description_fr?.trim() || null,
        description_en: formData.description_en?.trim() || null,
        is_active: formData.is_active,
        order: parseInt(formData.order) || 0
      };
      
      // Ensure we never send id, created_at, or updated_at for new records
      // These are auto-generated by the database
      delete categoryData.id;
      delete categoryData.created_at;
      delete categoryData.updated_at;

      let data, error;
      
      if (editingCategory) {
        // Update existing category
        const { data: updateData, error: updateError } = await supabase
          .from('category_gallery')
          .update(categoryData)
          .eq('id', editingCategory.id)
          .select('id, name_ar, name_fr, name_en, slug, description_ar, description_fr, description_en, is_active, order, created_at, updated_at');
        data = updateData && updateData.length > 0 ? updateData[0] : null;
        error = updateError;
      } else {
        // Create new category - use single() to get one result instead of array
        const { data: insertData, error: insertError } = await supabase
          .from('category_gallery')
          .insert(categoryData)
          .select('id, name_ar, name_fr, name_en, slug, description_ar, description_fr, description_en, is_active, order, created_at, updated_at')
          .single();
        data = insertData;
        error = insertError;
      }

      if (error) {
        console.error('Error saving category:', error);
        console.error('Error details:', {
          code: error.code,
          message: error.message,
          details: error.details,
          hint: error.hint,
          statusCode: error.statusCode
        });
        
        let errorMessage = 'Erreur lors de la sauvegarde: ';
        
        // Provide more specific error messages
        if (error.code === '23505') {
          if (error.message?.includes('pkey') || error.message?.includes('primary key')) {
            errorMessage += 'Erreur de clé primaire: la séquence de la base de données est désynchronisée. ';
            errorMessage += 'Veuillez exécuter le script SQL: sql/fix_category_gallery_sequence.sql dans Supabase SQL Editor pour corriger ce problème.';
          } else if (error.message?.includes('slug') || error.message?.includes('unique')) {
            errorMessage += 'Un slug ou une valeur unique existe déjà. Veuillez utiliser une valeur différente.';
          } else {
            errorMessage += 'Une valeur unique existe déjà. Veuillez utiliser une valeur différente.';
          }
        } else if (error.message?.includes('duplicate') || error.message?.includes('unique') || error.statusCode === 409) {
          errorMessage += 'Un slug ou une valeur unique existe déjà. Veuillez utiliser une valeur différente.';
        } else if (error.code === '23503' || error.message?.includes('foreign key')) {
          errorMessage += 'Erreur de référence. Vérifiez les relations.';
        } else if (error.code === '23514' || error.message?.includes('check constraint')) {
          errorMessage += 'Les données ne respectent pas les contraintes de validation.';
        } else if (error.code === 'PGRST116' || error.message?.includes('permission') || error.message?.includes('policy')) {
          errorMessage += 'Erreur de permissions. Vérifiez les politiques RLS.';
        } else {
          errorMessage += error.message || error.details || 'Erreur inconnue';
        }
        
        showNotification(errorMessage, 'error');
        return;
      }

      showNotification(editingCategory ? 'Catégorie mise à jour avec succès' : 'Catégorie créée avec succès');
      await loadCategories();
      setShowForm(false);
      setEditingCategory(null);
      resetForm();
    } catch (err) {
      console.error('Exception saving category:', err);
      showNotification('Erreur de connexion: ' + err.message, 'error');
    }
  };

  const handleEdit = (category) => {
    setEditingCategory(category);
    setFormData({
      name_ar: category.name_ar || '',
      name_fr: category.name_fr || '',
      name_en: category.name_en || '',
      slug: category.slug || '',
      description_ar: category.description_ar || '',
      description_fr: category.description_fr || '',
      description_en: category.description_en || '',
      is_active: category.is_active !== undefined ? category.is_active : true,
      order: category.order || 0
    });
    setShowForm(true);
  };

  const handleDelete = async (id) => {
    if (window.confirm('Êtes-vous sûr de vouloir supprimer cette catégorie ?')) {
      try {
        setError('');
        
        const { error } = await supabase
          .from('category_gallery')
          .delete()
          .eq('id', id);

        if (error) {
          console.error('Error deleting category:', error);
          showNotification('Erreur lors de la suppression: ' + error.message, 'error');
          return;
        }

        showNotification('Catégorie supprimée avec succès');
        await loadCategories();
      } catch (err) {
        console.error('Exception deleting category:', err);
        showNotification('Erreur de connexion: ' + err.message, 'error');
      }
    }
  };

  const handleCancel = () => {
    setShowForm(false);
    setEditingCategory(null);
    resetForm();
    setError('');
    setSuccess('');
  };

  const resetForm = () => {
    setFormData({
      name_ar: '',
      name_fr: '',
      name_en: '',
      slug: '',
      description_ar: '',
      description_fr: '',
      description_en: '',
      is_active: true,
      order: 0
    });
  };

  const filteredCategories = categories.filter(category => {
    const matchesSearch = 
      (category.name_ar || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (category.name_fr || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (category.name_en || '').toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = 
      filterStatus === 'all' || 
      (filterStatus === 'active' && category.is_active) ||
      (filterStatus === 'inactive' && !category.is_active);
    return matchesSearch && matchesStatus;
  });

  if (loading && categories.length === 0) {
    return (
      <div className="admin-gallery-categories">
        <div className="loading">Chargement des catégories...</div>
      </div>
    );
  }

  return (
    <div className="admin-gallery-categories">
      <div className="admin-crud-header">
        <h2>Gestion des Catégories de Galerie</h2>
        <button className="btn-add" onClick={() => { setShowForm(true); setEditingCategory(null); resetForm(); }}>
          + Ajouter une Catégorie
        </button>
      </div>

      {(error || success) && (
        <div className={`notification ${error ? 'error' : 'success'}`}>
          {error || success}
        </div>
      )}

      {showForm && (
        <div className="form-modal">
          <div className="form-content">
            <h3>{editingCategory ? 'Modifier la Catégorie' : 'Ajouter une Catégorie'}</h3>
            <form onSubmit={handleSubmit}>
              <div className="form-row">
                <div className="form-group">
                  <label>Nom (Arabe) *</label>
                  <input
                    type="text"
                    name="name_ar"
                    value={formData.name_ar}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Nom (Français) *</label>
                  <input
                    type="text"
                    name="name_fr"
                    value={formData.name_fr}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Nom (Anglais) *</label>
                  <input
                    type="text"
                    name="name_en"
                    value={formData.name_en}
                    onChange={handleInputChange}
                    required
                  />
                </div>
              </div>

              <div className="form-group">
                <label>Slug (optionnel)</label>
                <input
                  type="text"
                  name="slug"
                  value={formData.slug}
                  onChange={handleInputChange}
                  placeholder="Auto-généré si vide"
                />
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Description (Arabe)</label>
                  <textarea
                    name="description_ar"
                    value={formData.description_ar}
                    onChange={handleInputChange}
                    rows="3"
                  />
                </div>
                <div className="form-group">
                  <label>Description (Français)</label>
                  <textarea
                    name="description_fr"
                    value={formData.description_fr}
                    onChange={handleInputChange}
                    rows="3"
                  />
                </div>
                <div className="form-group">
                  <label>Description (Anglais)</label>
                  <textarea
                    name="description_en"
                    value={formData.description_en}
                    onChange={handleInputChange}
                    rows="3"
                  />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Ordre</label>
                  <input
                    type="number"
                    name="order"
                    value={formData.order}
                    onChange={handleInputChange}
                    min="0"
                  />
                </div>
                <div className="form-group checkbox-group">
                  <label>
                    <input
                      type="checkbox"
                      name="is_active"
                      checked={formData.is_active}
                      onChange={handleInputChange}
                    />
                    Actif
                  </label>
                </div>
              </div>

              <div className="form-actions">
                <button type="submit" className="btn-save">
                  {editingCategory ? 'Mettre à jour' : 'Créer'}
                </button>
                <button type="button" className="btn-cancel" onClick={handleCancel}>
                  Annuler
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      <div className="filters-section">
        <input
          type="text"
          placeholder="Rechercher..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="search-input"
        />
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className="filter-select"
        >
          <option value="all">Tous</option>
          <option value="active">Actifs</option>
          <option value="inactive">Inactifs</option>
        </select>
      </div>

      <div className="table-container">
        <table className="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nom (FR)</th>
              <th>Nom (AR)</th>
              <th>Slug</th>
              <th>Ordre</th>
              <th>Statut</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredCategories.length === 0 ? (
              <tr>
                <td colSpan="7" className="no-data">Aucune catégorie trouvée</td>
              </tr>
            ) : (
              filteredCategories.map((category) => (
                <tr key={category.id}>
                  <td>{category.id}</td>
                  <td>{category.name_fr}</td>
                  <td>{category.name_ar}</td>
                  <td>{category.slug}</td>
                  <td>{category.order}</td>
                  <td>
                    <span className={`status ${category.is_active ? 'active' : 'inactive'}`}>
                      {category.is_active ? 'Actif' : 'Inactif'}
                    </span>
                  </td>
                  <td>
                    <button className="btn-edit" onClick={() => handleEdit(category)}>
                      Modifier
                    </button>
                    <button className="btn-delete" onClick={() => handleDelete(category.id)}>
                      Supprimer
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default AdminCategoryGalleryCrud;

